# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acab27e9800794ad1bb8783f754fc315e459fe371f5a8ecdec413a431d2a4d506826823b688421e73bfa40d4eee9fa4f8a8e40cb44d08d3e7ad75b399e2199d7

test:
  secret_key_base: ac291fd979263ee78c212a6a3b96bd4d87cea7f196bd20cafc3e0b68021daa0b3d9dddfd383660b929d71ca2877b9509f427e3d6dc1916e4a264ee60d8b97202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
